#
# GENERATED FILE
#

[package]
name = "rsspice_tspice"
version = "0.1.0"
edition = "2024"

[dependencies]
f2rust_std = { path = "../../f2rust_std" }
rsspice_spicelib = { path = "../rsspice_spicelib" }
rsspice_support = { path = "../rsspice_support" }
rsspice_testutil = { path = "../rsspice_testutil" }
