#
# GENERATED FILE
#

[package]
name = "rsspice_tspice-2"
version = "0.1.0"
edition = "2024"

[dependencies]
f2rust_std = { path = "../../f2rust_std" }
rsspice_spicelib = { path = "../rsspice_spicelib" }
rsspice_support = { path = "../rsspice_support" }
rsspice_testutil = { path = "../rsspice_testutil" }
rsspice_tspice-1a = { path = "../rsspice_tspice-1a" }
rsspice_tspice-1b = { path = "../rsspice_tspice-1b" }
rsspice_tspice-1c = { path = "../rsspice_tspice-1c" }
rsspice_tspice-1d = { path = "../rsspice_tspice-1d" }
