[package]
name = "rsspice_api"
version = "0.1.0"
edition = "2024"

[dependencies]
f2rust_std = { path = "../../f2rust_std" }
rsspice_spicelib = { path = "../rsspice_spicelib" }
thiserror = "2.0.12"

[dev-dependencies]
approx = "0.5.1"
nalgebra = "0.33.2"
