#
# GENERATED FILE
#

[package]
name = "rsspice_support"
version = "0.1.0"
edition = "2024"

[dependencies]
f2rust_std = { path = "../../f2rust_std" }
rsspice_spicelib = { path = "../rsspice_spicelib" }
